import random

# Answer list for thanks
random_thanks = [
'De nada! Estarei aqui se precisar de mim!!',
'Por nada! Estarei aqui se precisar de mim!!',
'Fico feliz em ajudar! Estarei aqui se precisar de mim!!',
'Não há de quê! Estarei aqui se precisar de mim!!',
'É um prazer ajudar! Estarei aqui se precisar de mim!!',
'Sem problemas! Estarei aqui se precisar de mim!!',
'Estou aqui para ajudar! Estarei aqui se precisar de mim!!',
'Sempre à disposição! Estarei aqui se precisar de mim!!',
'Nada a agradecer! Estarei aqui se precisar de mim!!',
'O prazer foi meu! Estarei aqui se precisar de mim!!',
'É uma satisfação poder ajudar! Estarei aqui se precisar de mim!!',
'Conte comigo! Estarei aqui se precisar de mim!!',
'Estou disponível para ajudar! Estarei aqui se precisar de mim!!',
'Sempre que precisar, estou aqui! Estarei aqui se precisar de mim!!',
'Estou feliz em poder contribuir! Estarei aqui se precisar de mim!!',
'Ora essa! Estarei aqui se precisar de mim!!',
'Foi um prazer poder ser útil! Estarei aqui se precisar de mim!!',
'É uma honra ajudar! Estarei aqui se precisar de mim!!',
'A qualquer momento estou à disposição! Estarei aqui se precisar de mim!!',
'Não precisa agradecer! Estarei aqui se precisar de mim!!',
'Às ordens! Estarei aqui se precisar de mim!!',
'Estou sempre aqui para apoiar! Estarei aqui se precisar de mim!!',
'Sinta-se à vontade para perguntar! Estarei aqui se precisar de mim!!',
'Estou contente em poder ajudar! Estarei aqui se precisar de mim!!',
'Estou sempre pronto para ajudar! Estarei aqui se precisar de mim!!',
'Estou disponível 24 horas! Estarei aqui se precisar de mim!!',
'Obrigado por me permitir ajudar! Estarei aqui se precisar de mim!!',
'Obrigado por contar comigo! Estarei aqui se precisar de mim!!',
'Se precisar de algo, é só chamar! Estarei aqui se precisar de mim!!',
'Agradecido em poder ser útil! Estarei aqui se precisar de mim!!',
'Foi uma alegria poder ajudar! Estarei aqui se precisar de mim!!',
'Estou feliz em fazer parte da solução! Estarei aqui se precisar de mim!!',
'Conte sempre comigo! Estarei aqui se precisar de mim!!',
'Estou aqui para facilitar sua vida! Estarei aqui se precisar de mim!!',
'Obrigado por confiar em mim! Estarei aqui se precisar de mim!!',
'A satisfação é toda minha! Estarei aqui se precisar de mim!!',
'Obrigado por me dar a oportunidade de ajudar! Estarei aqui se precisar de mim!!',
'É sempre um prazer poder ajudar! Estarei aqui se precisar de mim!!',
'Obrigado por me permitir ser útil! Estarei aqui se precisar de mim!!',
'Agradeço a confiança depositada em mim! Estarei aqui se precisar de mim!!',
'Agradeço por contar com meu apoio! Estarei aqui se precisar de mim!!',
'É gratificante poder ajudar! Estarei aqui se precisar de mim!!',
'Obrigado pela parceria! Estarei aqui se precisar de mim!!',
'Estou à disposição para o que precisar! Estarei aqui se precisar de mim!!',
'Agradeço por me escolher como seu assistente! Estarei aqui se precisar de mim!!',
'Obrigado por me dar a chance de ajudar! Estarei aqui se precisar de mim!!',
'Fico satisfeito em poder ser de ajuda! Estarei aqui se precisar de mim!!',
]

#Function to reply thanks with a random message
def answer_thanks():
    return random.choice(random_thanks)
